language: node_js
node_js:
  - "6.9"
  - "7.1"
sudo: false
cache:
  directories:
    - $HOME/.yarn-cache
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
env:
  matrix:
  - NODE_ENV='ci'
  global:
  - secure: lC+SUm2cVW+6E6utt45i5NDe+zrrjbNtB+F4qFLOm8edTLl/ZMRas6atRCcrSBUQdGIfFsH/cN7+HHI2qwz/1nQtX4Oe/K4glVBj8zb87C1W5/l0kDk1QWlCubm2++CCjqGG+G9iOsMaXNxxeeo4M1GhCOTFCOLud2kzhNWY1Y1e+WbAESJpYrAtxo1gB1SmDhHzhnsHL+27JeQ1DVakNLRfO8FIaaFwjoq6W3zRGM80M3xGpqSyoHNp5DWWKJzqyAIsdmQmm9ik55Lx5+eFq4iV+gvniY15cWFzb7+tskFli7CsMmH04glKxlQJV5it5vHDNoB5f6wSDRb3T+7knxaVcjIltWZd3zF3TBkndym2pavb4c+kH3lYznM7ExsDQtULeU0c4GeDiZKARUhqBq2ZHi1t4IyvHYsOcjSG00UGFxBzTfTtCpmTfZypnXbHbuS5oDq1aKlOuL2UA5hS1S77BHaB1nTOVRmxPscqoix9KLhPOQdJWMEQwONz5lJUinTELLO7mwqnph4mO9hhix3NalXFGxScBvi7aP0zdD/H2q+bzliEzLXZd/BuoVmqcSU2dgYeocLYxFy4mBzypnfQE/FXWIpUBOL+vWdX9uCeCYUgB/1Dtxgp4pFPPG/suMBkbU2WZUBkAwX5m3LIc1jM+d8mROxAlzbr3TTDx24=
  - secure: fEXjYYuNUHO4+cX/rpRnE39LLfSbIpIepgMmvRiJWDS/0O16vYl4SBvj8h/pShnmRlVX5yhyd4XAS0yZODReq0AjZetupsfmnUXDRhVTe0CbYnR/CVBUTiO2rUcuFxSAuaqgoE1x6wNT8pwvcp+G5dh1RKSl/Z8pdLggg6slVvRRo9LV9ddiZvJKwBh3R8mPltI/9HQHD8ym2UESN7hUcB/oMDd84pnGU5/ce4UHzeMaqd+jL0GUH+ab8kiTe+GbrKXouT0RyiBVGgJAjtDruaDr7wBpAJ+5yqo5qsO5atansLECPE6NVHpFjtLEx0JA96VLh7Kp0wHV9JNJmlrsi+wHSwXrfD5nnQdtSwiWcTXL7+k8txRblUTnFTsHMhJzI6dB67k5wniw/MbVvYgIfrPnOgIFeooe1hQco+Mmo6Rtuz5ihWDFbp2ATZXRYMl6iDHrU9ncXnrt+eU7ct+BCtlEtBAHOZ7831tu4+BvYdkeGfHA1gCSmmJJkdhWdRMbxslLDJ2OdTnL3F2+ehb5mnqMo3q160OkpCnrsO9yMfrEYkfqImTby+4Zt1wS4lQxd6bP7V+osZ1pVUXdDwTXPMMeZvS/Z3Z1NUyR6TPJ6bYJ5IcMdtOpVFKejey9yXnn5vpvg2poc0fFm86c1GWFkMLSC2tI/+Lzvgf5c6YuYBI=
script:
  - react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bu‌​ndle --assets-dest android/app/src/main/res/
  - react-native bundle --platform ios     --dev false --entry-file index.ios.js     --bundle-output ios/main.jsbundle --assets-dest ios
matrix:
  include:
    - language: android
      os: linux
      jdk: oraclejdk8
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      sudo: required
      node_js: false
      before_install:
        - nvm install 7
        - node --version
        - travis_retry curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
        - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
        - travis_retry sudo apt-get update -qq
        - travis_retry sudo apt-get install -y -qq yarn
        - openssl aes-256-cbc -K $encrypted_26b4962af0e7_key -iv $encrypted_26b4962af0e7_iv
          -in debug.keystore.enc -out debug.keystore -d
      install:
        - yarn
      android:
        components:
          - build-tools-23.0.1
          - android-23
          - extra-android-m2repository
          - extra-google-google_play_services
          - extra-google-m2repository
          - addon-google_apis-google-16

      script:
        - cd android && ./gradlew assembleDebug && ./gradlew assembleRelease
      before_deploy:
      - cp $TRAVIS_BUILD_DIR/.keystore $HOME
      - jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 $TRAVIS_BUILD_DIR/android/app/build/outputs/apk/app-release-unsigned.apk $TRAVIS_BUILD_DIR/android/app/build/outputs/apk/app-debug-signed.apk -keystore $HOME/.keystore -storepass $storepass -keypass $keypass
      - "${ANDROID_HOME}/build-tools/22.0.1/zipalign 4 $TRAVIS_BUILD_DIR/android/app/build/outputs/apk/app-release-unsigned.apk $TRAVIS_BUILD_DIR/android/app/build/outputs/apk/app-debug-signed.apk"
      deploy: # mostly generated by `> travis deploy releases`
        skip_cleanup: true
        provider: releases
        api_key:
          secure: 2fYSjSPMmTUDhcgd6w/nXVMtsp6O+GHb0gFjpTjPA33xodEYsNlEvmdk9fvUJakWi2z0VxBaGw1iHaYCQmzj8858caQVjlSpdTRUVw3d/CMw0O3kZWKD37GaX5ocY1LZ2QSJS1ePXitOZYkgqbfK104Tiuru1/SKKziLgM5OIHVQj4CGdlvqRr5rERU2Sy9yPi+XgrlnTgcNGIzZ+3In19jhaZzFLvVTQckk0R6oQaQQnt/GudEPdft2SNLQS0ecHuUj8n8dGb0TR2G9ej5gVq7aDo4oyn2k8FOKa86XwT6cGpjm3VdOb5rfvAVxglm4GqWWjxXkm8Wq69Awrhb6PDHGvq1H68ShvEudSPr1ABRj6grWsf8n5IxKQL4FG+pV2d3D6wtD/mnljguvCjw8Gb652VFwij/Vhm4z8W/VvviUXF+sWnivdEOgvUOG3XW9DZP84I1IWPLSfj2nVnmgVYJVIrCmcSWh2B2iednJeWP75mz5PyXfUp+Q9ECuu0C19oi7C2pTHTqq3GhXAhtZszmllW4cRftw7kUYsyzDzVutB8SVSkKqSCiO/NXIfvbaHQ1BHabzV5aAhD1n2fitB7UDROaXZSlAWzq2eSpbKzITHmkUateEgig89oDIE9NUJ/iITTtWzGjqTxwQkhpFWN6HUSIJleC0658kgI/izwI=
        file: $TRAVIS_BUILD_DIR/android/app/build/outputs/apk/app-debug-signed.apk
        on:
          repo: CodeLanka/ez-net-app
          tags: true
    - language: objective-c
      os: osx
      osx_image: xcode8.2
      node_js: false
      before_install:
        - nvm install 7
        - node --version
        - travis_retry npm install -g yarn
        - yarn -version
      install:
        - travis_retry gem install xcpretty
        - travis_retry yarn
      xcode_project: ios/ReactNativeProject.xcodeproj
      xcode_scheme: ios/ReactNativeProjectTests
      script:
        - cd ios
        - xcodebuild -scheme ReactNativeProject -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
